# Generated by Django 3.2.5 on 2021-07-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Вид табака')),
                ('slug', models.SlugField(max_length=75, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название продукта')),
                ('is_nicotine', models.BooleanField(default=True, verbose_name='Содержание никотина')),
                ('brand', models.CharField(max_length=75, verbose_name='Бренд')),
                ('maker_country', models.CharField(max_length=100, verbose_name='Страна производитель')),
                ('description', models.TextField()),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('strength', models.CharField(choices=[('1', 'Очень низкая'), ('2', 'Низкая'), ('3', 'Средняя'), ('4', 'Высокая'), ('5', 'Очень высокая')], max_length=100, verbose_name='Крепкость')),
                ('smoking', models.CharField(choices=[('1', 'Очень низкая'), ('2', 'Низкая'), ('3', 'Средняя'), ('4', 'Высокая'), ('5', 'Очень высокая')], max_length=100, verbose_name='Дымность')),
                ('taste', models.CharField(max_length=100, verbose_name='Вкус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('awailable', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smokeshop.category')),
            ],
        ),
    ]
