# Generated by Django 3.2.5 on 2021-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smokeshop', '0002_auto_20210726_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
